### ISSUE TITLE
Unable to create account on self hosted web app due to mixed content rules

### ISSUE THREAD

**Issue by ctag** [standardnotes/server#1042]
**Describe the issue**
Hi,

The standardnotes documentation [here](https://standardnotes.com/help/47/can-i-self-host-standard-notes) lists self-hosting the client notes app as supported, but links to the ostensibly-defunct docker image [standardnotes/web](https://hub.docker.com/layers/standardnotes/web/stable/images/sha256-bf99c33bad03ca9ccd79c40e6aece368a6c23b887f95fcfeeaab86f68f0e3878?context=explore). 

I can see in other forum discussion that the web docker image has been replaced by something else. Is it possible to self-host the replacement notes client app, or is the documentation on this page no longer applicable?

**Comment by moughxyz** [comment]
You can not use app.standardnotes.com to connect with your own server. This is a recent change:

> app.standardnotes.com will no longer allow connections to arbitrary backends. This is a security enhancing mechanism that will prevent the main web app from being able to access external servers in the event of a theoretical XSS vulnerability. You will still however be able to connect to your server from the desktop and mobile app, and of course you can always self-host the web app.

This will be instated soon. The issue you're seeing is that https pages cannot connect to http servers.

You'll need to self-host the web app: https://github.com/standardnotes/app?tab=readme-ov-file#docker-setup

**Comment by ctag** [comment]
@moughxyz thank you for your response. I will look into self hosting the web app. 

This question may be out of scope for this issue, but is the docker image considered current? It was last updated [2 years ago](https://hub.docker.com/r/standardnotes/web).

**Comment by moughxyz** [comment]
Looks like we stopped maintaining the docker image after migrating away from it internally. We will look into resupporting it now that self-hosting the web app is a more likely use case.

**Comment by effieeee** [comment]
Docker image is now updated with instructions on our website! 
https://standardnotes.com/help/self-hosting/web-app

Self hosting without Docker:
https://github.com/standardnotes/app?tab=readme-ov-file#self-hosting-the-web-app

**Comment by markusthiel** [comment]
> Docker image is now updated with instructions on our website! https://standardnotes.com/help/self-hosting/web-app
> 
> Self hosting without Docker: https://github.com/standardnotes/app?tab=readme-ov-file#self-hosting-the-web-app

It just does not work like that as you can see for example in https://github.com/standardnotes/server/issues/868
