### ISSUE TITLE
Cannot connect to self hosted site.

### ISSUE THREAD

**Issue by jschwalbe** [standardnotes/server#1043]
I followed directions here: https://github.com/standardnotes/app?tab=readme-ov-file#docker-setup but when I try to load the web content, it times out (refused to connect). 

my docker-compose.yml
```
services:
  web:
    image: standardnotes/web:stable
    env_file: .env
    ports:
      - 3001:3001
    restart: unless-stopped
```
the server is running at https://notes-api.example.com and yields
`Welcome to the Standard Notes server infrastructure. Learn more at https://docs.standardnotes.com` when I visit the URL.
the `.env` file has
`DEFAULT_SYNC_SERVER=https://notes-api.example.com`

When running the self-hosted web (2 yrs old on docker!!) it shows this:
```
# docker compose up
[+] Running 2/2
 ✔ Network notes-app_default  Created                                                0.1s 
 ✔ Container notes-app-web-1  Created                                                5.4s 
Attaching to web-1
web-1  | Prestart Step 1/1 - Removing server lock
web-1  | Starting Server...
web-1  | lerna-lite notice cli v1.6.0
web-1  | lerna-lite info versioning independent
web-1  | lerna-lite notice filter including "@standardnotes/web-server"
web-1  | lerna-lite info filter ["@standardnotes/web-server"]
web-1  | lerna-lite info Executing command in 1 package: "yarn run start"
```

Any further assistance would be appreciated! Thanks

**Comment by Vaslo** [comment]
Did you ever figure this out?  I got the server running but having the same timeout issue with the simple compose like you have.

**Comment by jschwalbe** [comment]
Nope. Moved on.

**Comment by smaciver** [comment]
Just ran across this regarding the web app part but the I believe compose file needs to be ports: 3001:3000 not 3001:3001. I just used the same structure and it works. From notes the container is expected to be port 3000 internally but I'm assuming like me it's already in use so you changed it. But just need to change the external side. Hope that helps.
