### ISSUE TITLE
self host Unsupported api version: 20240226

### ISSUE THREAD

**Issue by WakeOneT** [standardnotes/server#1046]
mac client 3.191.18

self host server https://hub.docker.com/r/standardnotes/server

![CleanShot 2024-03-12 at 20 12 33@2x](https://github.com/standardnotes/server/assets/124677933/eb8a45bb-8cc6-4cd2-b606-f8193dba11f1)

**Comment by nevertomorrow** [comment]
+1 here, I just installed both server and web on my VPS through docker, got same error `Unsupported api version: 20240226` while trying to signup from mac app.
And I also tried to signup from web, it shows `Failed to fetch` 

I'm using Traefik as the reverse proxy for both server and web. 

Any idea for further debugging? 

Thanks

**Comment by effieeee** [comment]
Hi all, please update your Docker servers! You should find that the issue has been fixed 🙏

**Comment by cloudyshoreline** [comment]
Hi, @effieeee , thanks for the update. I downloaded the latest docker server image and rebuilt the container, however, this time, it showed: `NetworkError when attempting to fetch resource.` during signup. Is there any place/logs I should check to figure out what went wrong? Thanks a lot.
