### ISSUE TITLE
CORS error 

### ISSUE THREAD

**Issue by WakeOneT** [standardnotes/server#1047]
server docker is new ! 

web docker is 3.191.21

I tested all the previous versions 3.189.4 before including this one without any problems

![CleanShot 2024-03-12 at 20 15 46@2x](https://github.com/standardnotes/server/assets/124677933/17ad32db-217c-455f-b7b3-ffa377d35edd)

**Comment by WakeOneT** [comment]
This error causes, if sync is not in the same domain as the web, it can't synchronize and can't access the resource

**Comment by navjotjsingh** [comment]
What's the solution?
