### ISSUE TITLE
Add "version" to docker-compose.yml Sample

### ISSUE THREAD

**Issue by wizcabbit** [standardnotes/server#445]
How about add "version" attribute in docker-compose.yml default sample file like:

version: "3"

at least on my server, I have to add this line to make docker-compose work well

**Comment by karolsojko** [comment]
The `version` attribute is deprecated as per docs: 

> The Compose file is a [YAML](http://yaml.org/) file defining [version](https://docs.docker.com/compose/compose-file/#version-top-level-element) (DEPRECATED), [services](https://docs.docker.com/compose/compose-file/#services-top-level-element) (REQUIRED), [networks](https://docs.docker.com/compose/compose-file/#networks-top-level-element), [volumes](https://docs.docker.com/compose/compose-file/#volumes-top-level-element), [configs](https://docs.docker.com/compose/compose-file/#configs-top-level-element) and [secrets](https://docs.docker.com/compose/compose-file/#secrets-top-level-element).

https://docs.docker.com/compose/compose-file/#compose-file 

The docker-compose file we provide is a "just-enough" sample. Feel free to add anything you want in there to fit your needs.
