### ISSUE TITLE
Subscriptions on your self-hosted server

### ISSUE THREAD

**Issue by yremac** [standardnotes/server#461]
What does a subscription do on its server? All that happens to me is a notification with congratulations about the subscription, in the end it is not there? what does this function do?
use windows client

**Comment by jackyzy823** [comment]
> What does a subscription do on its server?

enables server-side features: Note history , Encrypted files etc.

**Comment by yremac** [comment]
None of the premium features work for me

**Comment by jackyzy823** [comment]
Can you access "Files" in sideview? If you can, then the premium features works.

**Comment by yremac** [comment]
I realized that this is not suitable for me and I just stop using it((
