### ISSUE TITLE
No matching manifest

### ISSUE THREAD

**Issue by heredia21** [standardnotes/server#463]
I am getting the following error when trying to set this up on Raspberry Pi 4:

no matching manifest for linux/arm/v7 in the manifest list entries

After running:

docker compose pull && docker compose up -d

**Comment by jackyzy823** [comment]
Your RPi4's kernel is 32bit (arm32v7).

However most docker images in the docker-compose file only provides arm64 images (like mysql , localstack and standardnotes/server). Only redis support arm32v7.

You could choose an linux system which provide arm64 kernel to reinstall your RPi4 . like https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/

**Comment by heredia21** [comment]
Thank you! I'll test this route and open a new ticket if there are any issues.
