### ISSUE TITLE
Self-hosted Notes not syncing after update

### ISSUE THREAD

**Issue by ChesterHCopperpot** [standardnotes/server#606]
Log: https://paste.debian.net/hidden/c8acd1ba/

Was working fine. Not sure what changed. I tried rebooting the server but no dice. Any help?
Note: I've never tried adding the Files functionality.
Also, not sure if it matters, but I am a paying subscriber.

Running `docker container list` shows:
https://paste.debian.net/hidden/f4b2ea1

**Comment by moughxyz** [comment]
In your .env file, set `DB_TYPE=mysql` and `CACHE_TYPE=redis`. Then restart the server.

**Comment by ChesterHCopperpot** [comment]
Gave me an error: `$ sudo ./server.sh start`

`The .env file contains different amount of lines than .env.sample. This may be caused by the fact that there is a new environment variable to configure. Please update your environment file and try again.`

Edited the .env.sample to add these lines. Still not syncing.

Log: https://paste.debian.net/hidden/c7b0d086/
