### ISSUE TITLE
Mysql db table error

### ISSUE THREAD

**Issue by mostdcoa** [standardnotes/server#829]
```
==> logs/api-gateway.log <==
localhost:3105 is unavailable yet - waiting for it to start

==> logs/revisions.log <==
query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'standard_notes_db' AND `TABLE_NAME` = 'migrations'
query: SELECT * FROM `standard_notes_db`.`migrations` `migrations` ORDER BY `id` DESC
110 migrations are already loaded in the database.
5 migrations were found in the source code.
AddVaultsUser1694157482134 is the last executed migration. It was executed on Fri Sep 08 2023 07:18:02 GMT+0000 (Coordinated Universal Time).
2 migrations are new migrations must be executed.
query: START TRANSACTION
query: ALTER TABLE `revisions_revisions` ADD `edited_by` varchar(36) NULL
query failed: ALTER TABLE `revisions_revisions` ADD `edited_by` varchar(36) NULL
error: Error: Table 'standard_notes_db.revisions_revisions' doesn't exist
query: ROLLBACK

==> logs/supervisord.log <==
2023-09-15 15:03:30,038 WARN exited: revisions (exit status 1; not expected)
2023-09-15 15:03:31,041 INFO spawned: 'revisions' with pid 1181

==> logs/revisions.log <==
localhost:3101 is up. Proceeding to startup.
```

The stack wont start and I think it's because of this error. For some reason it is looking for revisions_revisions?

**Comment by mostdcoa** [comment]
Ok, well I fixed this, and incase anybody has this same issue, I had to modified the database using these sql commands (start a phpmyadmin docker, set the env for PMA_HOST to the ip of your container, then use the username/password you used for your standard notes database, login to your phpmyadmin container, and then select your std_notes_db and run these sql commands:

ALTER TABLE `revisions` RENAME TO `revisions_revisions`;
ALTER TABLE `revisions_revisions` DROP COLUMN `edited_by`;

then the scripts were able to do the changes they needed to do to get it working again. This probably happened during an update and things just didn't get changed appropriately.

**Comment by mostdcoa** [comment]
This is contnuing to give me issues:

```
==> logs/revisions.log <==
5 migrations were found in the source code.
RemoveNotifications1695643525793 is the last executed migration. It was executed on Mon Sep 25 2023 12:05:25 GMT+0000 (Coordinated Universal Time).
2 migrations are new migrations must be executed.
query: START TRANSACTION
query: SELECT COUNT(*) as count FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = "revisions"
query: ALTER TABLE `revisions_revisions` ADD `edited_by` varchar(36) NULL
query failed: ALTER TABLE `revisions_revisions` ADD `edited_by` varchar(36) NULL
error: Error: Duplicate column name 'edited_by'
query: ROLLBACK
localhost:3101 is up. Proceeding to startup.
```

**Comment by tobiashochguertel** [comment]
@mostdcoa best is to write to the devs / support team help@standardnotes.com and point to this issue. I fixed it with your informations and sql commands.

**Comment by mostdcoa** [comment]
Thanks, I was able to fix it again this morning by renaming the edited_by column, making a new column with the same name, and dropping the modified/old one.

Just a pain that this issue is happening, although great in that I'm learning more about SQL.
