### ISSUE TITLE
Failure to log in

### ISSUE THREAD

**Issue by ChesterHCopperpot** [standardnotes/server#836]
I selfhost (and am a paying subscriber) but since a recent update my apps don't log in anymore. Can you help me understand what I need to do to fix this?

Thank you.

Log output:

db_self_hosted | 2023-09-18T17:10:24.412219Z 15 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
server_self_hosted | 2023-09-18 17:10:24,533 WARN exited: revisions (exit status 1; not expected)
server_self_hosted | 2023-09-18 17:10:25,536 INFO spawned: 'revisions' with pid 177
db_self_hosted | 2023-09-18T17:10:26.076519Z 16 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
server_self_hosted | 2023-09-18 17:10:27,381 INFO success: revisions entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
db_self_hosted | 2023-09-18T17:10:29.778258Z 17 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
server_self_hosted | 2023-09-18 17:10:29,925 WARN exited: revisions (exit status 1; not expected)
server_self_hosted | 2023-09-18 17:10:30,929 INFO spawned: 'revisions' with pid 195
server_self_hosted | 2023-09-18 17:10:32,035 INFO success: revisions entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
db_self_hosted | 2023-09-18T17:10:35.701972Z 18 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
server_self_hosted | 2023-09-18 17:10:35,909 WARN exited: revisions (exit status 1; not expected)
server_self_hosted | 2023-09-18 17:10:36,913 INFO spawned: 'revisions' with pid 211
server_self_hosted | 2023-09-18 17:10:37,927 INFO success: revisions entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
db_self_hosted | 2023-09-18T17:10:40.381546Z 19 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
server_self_hosted | 2023-09-18 17:10:40,513 WARN exited: revisions (exit status 1; not expected)
server_self_hosted | 2023-09-18 17:10:41,040 INFO spawned: 'revisions' with pid 227
server_self_hosted | 2023-09-18 17:10:42,051 INFO success: revisions entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
db_self_hosted | 2023-09-18T17:10:44.541190Z 20 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
server_self_hosted | 2023-09-18 17:10:44,665 WARN exited: revisions (exit status 1; not expected)
server_self_hosted | 2023-09-18 17:10:45,669 INFO spawned: 'revisions' with pid 241
server_self_hosted | 2023-09-18 17:10:46,681 INFO success: revisions entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
db_self_hosted | 2023-09-18T17:10:49.157444Z 21 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
server_self_hosted | 2023-09-18 17:10:49,273 WARN exited: revisions (exit status 1; not expected)
server_self_hosted | 2023-09-18 17:10:50,277 INFO spawned: 'revisions' with pid 255

**Comment by karolsojko** [comment]
Hi @ChesterHCopperpot 

can you give me the output of `tail logs/revisions*` ?

**Comment by ChesterHCopperpot** [comment]
https://paste.debian.net/hidden/8aadfca9/

**Comment by ChesterHCopperpot** [comment]
@karolsojko Thank you for all that you do :)

**Comment by karolsojko** [comment]
@ChesterHCopperpot cheers :) 🎉
