### ISSUE TITLE
cant download files 

### ISSUE THREAD

**Issue by Gr3nDiz3r** [standardnotes/server#914]
when try download exist file its show error while downloading file 

and the files.log have this 

i check and the file is exist in same place in disk where is already 

{"level":"error","message":"Could not get file metadata for resource: 2334354d-0328-4fab-b586-42401c7e2a0c/77b14b47-3409-45f6-a70d-1bd47b4b9d25","service":"files"}

also when i debug this request when try to download i se my file server url  reply like this

Could not get file metadata

**Comment by patrikgrill** [comment]
Check your "docker-compose"-file, there was a change:

https://github.com/standardnotes/server/commit/c2cbf4459466325d6f3473cfb28fb6ed7f74f0f2#diff-17a0c6751b015005ae01f2eb8831d191f7368148bbf639e8d460aecc772b7d83

<img width="993" alt="09-11-2023_11-42-08" src="https://github.com/standardnotes/server/assets/116505415/310c2d61-cacb-4f4b-9bbc-4fbd534182d7">

**Comment by Gr3nDiz3r** [comment]
Thanks its fix my issue
