### ISSUE TITLE
Auth-worker having issues with deserialization

### ISSUE THREAD

**Issue by clayrosenthal** [standardnotes/server#963]
Not sure what prompted this, but I see a bunch of error lines repeating this in `auth-worker.log`: 
```
"Error occured while handling SQS message: SQSError: SQS receive message failed: Unexpected token '<', \"<?xml vers\"... is not valid JSON\n  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.\n    at toSQSError
```

I am not sure how to get the full object that is failing to be deserialized. `auth-worker.err` doesn't have anything except dns errors on the cache, I'd imagine from bootup.

**Comment by karolsojko** [comment]
Hi @clayrosenthal ,

thanks for reporting. 

A couple of things to check here:
1) Can you check your `.env` file and see if you have `AUTH_JWT_SECRET`, `AUTH_SERVER_ENCRYPTION_SERVER_KEY` and `VALET_TOKEN_SECRET` set up there. If that is ok we can move on to step 2 if they are missing please do not proceed as you might lose your data.
2) Make sure you have your `.env` files consistent with the [example](https://raw.githubusercontent.com/standardnotes/server/main/.env.sample) - meaning there is no env var missing
3) Check if your localstack bootstrap script is not outdated compared to the [example one](https://raw.githubusercontent.com/standardnotes/server/main/docker/localstack_bootstrap.sh)
4) Finally try updating the stack with `docker compose pull && docker compose up -d` and check if that helps

**Comment by karolsojko** [comment]
@basiljelly thank you very much - I've updated the docs with this
